<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ProductHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['product_id']) || (! empty($this->class->fieldMappings['product_id']['nullable']) && array_key_exists('product_id', $data))) {
            $value = $data['product_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['product_id']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['product_id']->setValue($document, $return);
            $hydratedData['product_id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name']) || (! empty($this->class->fieldMappings['name']['nullable']) && array_key_exists('name', $data))) {
            $value = $data['name'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['name']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['price']) || (! empty($this->class->fieldMappings['price']['nullable']) && array_key_exists('price', $data))) {
            $value = $data['price'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['price']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['price']->setValue($document, $return);
            $hydratedData['price'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description']) || (! empty($this->class->fieldMappings['description']['nullable']) && array_key_exists('description', $data))) {
            $value = $data['description'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['description']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['colors']) || (! empty($this->class->fieldMappings['colors']['nullable']) && array_key_exists('colors', $data))) {
            $value = $data['colors'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['colors']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['colors']->setValue($document, $return);
            $hydratedData['colors'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['sizes']) || (! empty($this->class->fieldMappings['sizes']['nullable']) && array_key_exists('sizes', $data))) {
            $value = $data['sizes'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['sizes']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['sizes']->setValue($document, $return);
            $hydratedData['sizes'] = $return;
        }
        return $hydratedData;
    }
}